version: "3.4"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test