name: PR

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} using dotnet version ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal