name: PR

on:
  pull_request:

jobs:
  build-sss-f:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        working-directory: src/SqlStreamStore.FSharp
        run: dotnet build --no-restore --configuration Release

  build-sss-f-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        working-directory: src/SqlStreamStore.FSharp.Postgres
        run: dotnet build --no-restore --configuration Release